# SPDX-FileCopyrightText: 2025-2026 The Heat Pump Mining Authors, see AUTHORS.md
#
# SPDX-License-Identifier: Apache-2.0

name: CI/CD

env:
  SINGULARITY_VERSION: 4.3.5

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for version number generation
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - run: |
          DEBIAN_FRONTEND=noninteractive sudo apt-get install -y fakeroot
          wget https://github.com/sylabs/singularity/releases/download/v$SINGULARITY_VERSION/singularity-ce_$SINGULARITY_VERSION-$(lsb_release -cs)_amd64.deb
          sudo dpkg -i singularity-ce_$SINGULARITY_VERSION-$(lsb_release -cs)_amd64.deb || true
          DEBIAN_FRONTEND=noninteractive sudo apt-get install -fy
      - uses: gradle/actions/setup-gradle@v5
      - run: ./gradlew build kdocJar javadocJar sourcesJar runtimeZip singularityImage
      - uses: actions/upload-artifact@v6
        with:
          name: JARs
          path: build/libs/*.jar
      - uses: actions/upload-artifact@v6
        with:
          name: Distributions
          path: |
            build/distributions/*.tar
            build/distributions/*.zip
      - uses: actions/upload-artifact@v6
        with:
          name: Image
          path: build/image.zip
      - uses: actions/upload-artifact@v6
        with:
          name: Installers
          path: |
            build/jpackage/*.deb
            build/jpackage/*.rpm
      - uses: actions/upload-artifact@v6
        with:
          name: Singluarity
          path: build/singularity/*.sif
